### ISSUE TITLE
CANSparkMax Init Error

### ISSUE THREAD

**Issue by frc834** [FRCTeam834/Robot-2022#12]
********** Robot program starting **********
navX-Sensor Java library for FRC
Unhandled exception: java.lang.IllegalStateException: A CANSparkMax instance has already been created with this device ID: 1
Error at com.revrobotics.CANSparkMaxLowLevel.<init>(CANSparkMaxLowLevel.java:136): Unhandled exception: java.lang.IllegalStateException: A CANSparkMax instance has already been created with this device ID: 1
at com.revrobotics.CANSparkMaxLowLevel.<init>(CANSparkMaxLowLevel.java:136)
The robot program quit unexpectedly. This is usually due to a code error.
The above stacktrace can help determine where the error occurred.
See https://wpilib.org/stacktrace for more information.
at com.revrobotics.CANSparkMax.<init>(CANSparkMax.java:188)
at frc.robot.subsystems.swerve.SwerveModule.<init>(SwerveModule.java:105)
at frc.robot.subsystems.swerve.DriveTrain.<init>(DriveTrain.java:107)
The startCompetition() method (or methods called by it) should have handled the exception above.
at frc.robot.Robot.robotInit(Robot.java:62)
at edu.wpi.first.wpilibj.TimedRobot.startCompetition(TimedRobot.java:107)
at edu.wpi.first.wpilibj.RobotBase.runRobot(RobotBase.java:373)
at edu.wpi.first.wpilibj.RobotBase.startRobot(RobotBase.java:463)
at frc.robot.Main.main(Main.java:27)
Warning at edu.wpi.first.wpilibj.RobotBase.runRobot(RobotBase.java:388): The robot program quit unexpectedly. This is usually due to a code error.
The above stacktrace can help determine where the error occurred.
See https://wpilib.org/stacktrace for more information.
Error at edu.wpi.first.wpilibj.RobotBase.runRobot(RobotBase.java:395): The startCompetition() method (or methods called by it) should have handled the exception above.
[phoenix-diagnostics] Server shutdown cleanly. (dur:10|0)
[phoenix] Library shutdown cleanly
[phoenix-diagnostics] Server shutdown cleanly. (dur:10|0)

**Comment by Benaiah2320** [comment]
Turn it off and back on again

**Comment by CAP1Sup** [comment]
> Turn it off and back on again

What a wise suggestion

**Comment by CAP1Sup** [comment]
This was due to the Drivetrain being created twice. Should be fixed now (PR #13), just needs to be tested

**Comment by CAP1Sup** [comment]
All fixed, everything is working as it should
